### ISSUE TITLE
Statistics plugin in bootcamp needs 

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi-plugins-bootcamp#2]
- I clone the gephi-plugins-bootcamp repo in Netbeans
- build the NBM for StatisticsPluginExample
- open Gephi, select the NBM, starts install

=> I get the warning:

"Some plugins require plugin org.jdesktop.swingx to be installed."

"The plugin org.jdesktop.swingx is requested in version 1.6.1."

=> can't go further.

In Netbeans, this plugin "org.jdesktop.swingx" is listed in the libraries of the StatisticsPluginExample, so I don't understand what's missing?

I use Netbeans 7.3.

Help!

**Comment by mbastian** [comment]
Correct me if I'm wrong but you're building the NBM using the bootcamp and loading it into a Gephi 0.8.2. The problem you have is probably because the bootcamp repository is still using the 0.8.1 version of the platform. As we made some changes from 0.8.1 to 0.8.2 some things aren't compatible anymore. Specifically, in 0.8.2 with the migration from Ant to Maven we centralize our third-party librairies into 2 modules: CoreLibraryWrapper and UILibraryWrapper. That means we removed some specific wrapper modules (like SwingX) and all modules that used to depend on that module should now depend on UILibraryWrapper.

Hopefully, we made it quite easy to update the platform version and I'm doing this as I'm writing. I'm updating this repository to use the 0.8.2 version of the platform. I reviewed the different modules (including StatisticsPluginExample) and made the dependency changes so it compiles properly. I don't have much time to test this right now but it should be okay.

Pull the repository and rebuild your NBM again. Let me know how it goes.

**Comment by seinecle** [comment]
Hi,

Thanks a lot! Indeed I was building from the bootcamp.
In the meantime I cloned the SNA plugin and adapted it to start mine, and
that worked. I'll get back to the examples of the bootcamp for my next
plugin!

Best,

Clement

---

Clement Levallois, PhD
Erasmus University Rotterdam
The Netherlands

pro websitehttp://www.erim.eur.nl/ERIM/People/Person_Details?p_aff_id=4321
 / personal website http://www.clementlevallois.net/

twitter and skype: @seinecle
Discover the NESSHI project: http://www.nesshi.eu
check my new app: http://www.umigon.com
